---
# tasks file for testing role
- name: Package Config
  ansible.builtin.include_tasks: testing_packages.yml
  tags: packages

- name: Service Config
  ansible.builtin.include_tasks: testing_services.yml
  tags: services
