---
# Enable VirtualBox services
- name: Service Config Block
  become: true
  tags: services
  block:
    - name: Start/enable testing services
      ansible.builtin.service:
        name: "{{ item }}"
        state: started
        enabled: true
      with_items: "{{ testing_services }}"
