---
# Install dependencies to run Molecule testing
- name: Package Config Block
  become: true
  tags: packages
  block:
    - name: Install testing packages
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      with_items: "{{ testing_packages }}"
