---
- name: System Config Block
  become: true
  tags: system
  block:
    - name: Verify NVIDIA drivers are accessible via nvidia-smi
      ansible.builtin.command:
        cmd: nvidia-smi
      changed_when: false
      register: jupyter_nvidia_smi_result

    - name: Display nvidia-smi output
      ansible.builtin.debug:
        var: jupyter_nvidia_smi_result.stdout_lines
