- name: Physical Machines
  hosts: physical
  roles:
    - common
    - physical

- name: Hypervisor
  hosts: esper
  roles:
    - proxmox

- name: Backup Server
  hosts: simic
  roles:
    - pbs

- name: GPU/Development Server
  hosts: abzan
  roles:
    - podman
    - podman_jupyter
    - sunshine
    - testing
